---
# tasks file for oh_my_zsh_colorls
- name: Installing dependences 1/7
  become: true
  apt:
    pkg:
      - git
      - ruby-full
      - gcc 
      - make
    state: present

- name: Downloading fonts 2/7
  become_user: '{{ item.username }}'
  git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    version: master
    dest: '~/nerd-fonts'
  with_items: '{{ users }}'
  when: users is defined
  
- name: Installing Fonts 3/7
  become_user: '{{ item.username }}'
  shell: cd ~/nerd-fonts $$ ./install.sh
  with_items: '{{ users }}'
  when: users is defined

- name: Removing temporal files 4/7
  become_user: '{{ item.username }}'
  file:
    state: absent
    path: ~/nerd-fonts
  with_items: '{{ users }}'
  when: users is defined

- name: Installing Colorls 5/7
  become: true
  shell: gem install colorls

- name: Adding config to .zshrc 6/7
  become_user: '{{ item.username }}'
  lineinfile:
    path: ~/.zshrc
    line: 'source $(dirname $(gem which colorls))/tab_complete.sh'
    state: present
  with_items: '{{ users }}'
  when: users is defined

- name: Replacing alias -ls- to .zshrc 7/7
  become_user: '{{ item.username }}'
  lineinfile:
    path: ~/.zshrc
    line: "alias ls='colorls'"
    state: present
  with_items: '{{ users }}'
  when: users is defined
